config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  get '/search', to: 'searches#search'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resource :comments, only: %i[create]
  end

  resources :questions, except: %i[edit], concerns: %i[votable commentable] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, except: %i[edit], concerns: %i[votable commentable] do
      patch :pick_the_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :badges, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: 'User'
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_one :badge, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation, :subscribe_author

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    questions = Question.all
    render json: questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: question
  end

  def create
    question = Question.new(question_params)
    question.author = current_resource_owner

    if question.save
      render json: question, status: :created
    else
      render json: question.errors, status: :unprocessable_entity
    end
  end

  def update
    if question.update(question_params)
      render json: question, status: :ok
    else
      render json: question.errors, status: :unprocessable_entity
    end
  end

  def destroy
    question.destroy
  end

  private

  def question
    @question ||= Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  after_action :publish_question, only: %i[create]

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.build
    @comment = Comment.new
  end

  def new
    question.links.build
    @badge = question.build_badge
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(question)
      question.update(question_params)
      flash[:notice] = 'Question was updated.'
    else
      head :forbidden
    end

    #subscription
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy

      redirect_to questions_path, notice: 'Question was deleted.'
    else
      head :forbidden
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def subscription
    @subscription ||= question.subscriptions.find_by(user: current_user)
  end

  helper_method :question, :subscription

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: %i[name url id _destroy],
                                     badge_attributes: %i[name img])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
        'questions',
        ApplicationController.render(
            partial: 'questions/question',
            locals: { question: question }
        )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
= form_with model: question, class: 'hidden', html: {id: "edit-question-#{question.id}"} do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
  p= f.submit 'Save question'

app/views/questions/_file.html.slim
- question.files.each do |file|
  p class="storage-#{file.id}"
    = link_to file.filename.to_s, url_for(file)
    - if current_user&.author_of?(question)
      '  |
      = link_to 'Delete file', file_path(file), method: :delete, remote: true

app/views/questions/_form.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

  p Badge:
  p
    = f.fields_for :badge do |b|
      p
        = b.label :name
        = b.text_field :name
      p
        = b.label :img
        = b.file_field :img

  p = f.submit 'Ask'

app/views/questions/_question.html.slim
div class="question question-#{question.id}"
  = link_to question.title, question_path(question)

app/views/questions/_question_part.html.slim
- if user_signed_in?
  = render 'votes/vote', resource: question

h1 = question.title
p = question.body

- if question.files.attached?
  .storages
    = render 'file', question: question

- if question.links.present?
  .links
    p Links:
    ul
      - question.links.each do |link|
        - if link.gist_url?
          p = gist(link.url)

        li class="link-#{link.id}"
          = link_to link.name, link.url
          - if current_user&.author_of?(question)
            '  |
            = link_to 'Delete link', link_path(link), method: :delete, remote: true

- if current_user&.author_of?(question)
  .settings
    = link_to 'Edit question','#', class: 'edit-question-link', data: { question_id: question.id }
    '  |
    = link_to 'Delete question', question_path(question), method: :delete

  = render 'edit_form'

- if can?(:create, Subscription)
  .subscribe-option
    = render 'subscriptions/subscription', resource: question

.comment-block
  = render 'comments/form', resource: question

hr

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

.question-errors
  = render 'shared/errors', resource: question

.questions
  = render @questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
- cache question do
  .question-errors
    = render 'shared/errors', resource: question

  div class = "question question-#{question.id}" data-resource-id=question.id
    = render 'question_part'

  .answers
    = render question.answers.sort_by_best

  = render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');

<% if !question.errors.present? %>
  $('.flash').append('<%= render 'shared/flash' %>');
  $('.question').html('<%= j render 'question_part' %>');
<% end %>