config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  get '/search', to: 'searches#search'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resource :comments, only: %i[create]
  end

  resources :questions, except: %i[edit], concerns: %i[votable commentable] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, except: %i[edit], concerns: %i[votable commentable] do
      patch :pick_the_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :badges, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :body, presence: true

  scope :sort_by_best, -> { order(best: :desc) }

  def set_the_best
    self.transaction do
      question.answers.update_all(best: false )
      update!(best: true)
      question.badge&.update!(user: author)
    end
  end

  after_create :send_new_answer_in_question

  private

  def send_new_answer_in_question
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  after_action :publish_answer, only: %i[create]

  include Voted

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    @answer.author = current_user
    @answer.save
    flash[:notice] = 'Your answer successfully created.'
  end

  def update
    if current_user.author_of?(answer)
      answer.update(answer_params)
      flash[:notice] = 'Answer was updated.'
    else
      head :forbidden
    end
  end

  def destroy
    if current_user.author_of?(answer)
      answer.destroy
      flash[:notice] = 'Answer was deleted.'
    else
      head :forbidden
    end
  end

  def pick_the_best
    if current_user.author_of?(answer.question)
      answer.set_the_best
      @question = answer.question
      flash[:notice] = 'Answer was picked.'
    else
      head :forbidden
    end
  end

  private

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : question.answer.new
  end

  def question
    @question = if params[:question_id]
                  Question.find(params[:question_id])
                else
                  answer.question
                end
  end

  helper_method :answer, :question

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url id _destroy])
  end

  def publish_answer
    return if @answer.errors.any?

    files = []
    answer.files.each do |file|
      files << { id: file.id, url: url_for(file), name: file.filename.to_s }
    end

    links = []
    answer.links.each do |link|
      hash = { id: link.id, name: link.name, url: link.url }
      hash[:gist] = link.gist(link.url) if link.gist_url?
      links << hash
    end

    ActionCable.server.broadcast(
        "answers-#{@answer.question_id}", { answer: @answer, links: links, files: files }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    answers = question.answers
    render json: answers, each_serializer: AnswersSerializer
  end

  def show
    render json: answer
  end

  def create
    answer = question.answers.new(answer_params)
    answer.author = current_resource_owner

    if answer.save
      render json: answer, status: :created
    else
      render json: answer.errors, status: :unprocessable_entity
    end
  end

  def update
    if answer.update(answer_params)
      render json: answer, status: :ok
    else
      render json: answer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    answer.destroy
  end

  private

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div class="answer-#{answer.id}"
    = render partial: 'answers/answer_part', locals: { answer: answer }

app/views/answers/_answer_part.html.slim
- cache answer do
  p Answer:
  - if user_signed_in?
    = render 'votes/vote', resource: answer

  p = answer.body

  - if answer.best?
    .best-answer
      p = 'Best answer'

  - if answer.files.attached?
    .storages
      = render 'file', answer: answer

  - if answer.links.present?
    .links
      p Links:
      ul
        - answer.links.each do |link|
          - if link.gist_url?
            p = gist(link.url)

          li class="link-#{link.id}"
            = link_to link.name, link.url
            - if current_user&.author_of?(answer)
              '  |
              = link_to 'Delete link', link_path(link), method: :delete, remote: true

  - if current_user&.author_of?(answer)
    .settings
      = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
      '  |
      = link_to 'Edit answer','#', class: 'edit-answer-link', data: { answer_id: answer.id }

    = render 'answers/edit_form', answer: answer

  - if current_user&.author_of?(question)
    = link_to 'Pick best answer', pick_the_best_answer_path(answer), method: :patch, remote: true

  .comment-block
    = render 'comments/form', resource: answer

  hr

app/views/answers/_edit_form.html.slim
= form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
  p = f.submit 'Save answer'

app/views/answers/_file.html.slim
- answer.files.each do |file|
  p class="storage-#{file.id}"
    = link_to file.filename.to_s, url_for(file)
    - if current_user&.author_of?(answer)
      '  |
      = link_to 'Delete file', file_path(file), method: :delete, remote: true

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

= form_with model: [question, @answer], class: 'new-answer' do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

  p= f.submit 'Sent answer'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.flash').append('<%= render 'shared/flash' %>');
  $('.answers').append('<%= j render answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.flash').append('<%= render 'shared/flash' %>');
$('.answer-' + <%= answer.id %>).remove('');

app/views/answers/pick_the_best.js.erb
$('.flash').append('<%= render 'shared/flash' %>');
$('.answers').html('<%= j render @question.answers.sort_by_best %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if !answer.errors.present? %>
  $('.flash').append('<%= render 'shared/flash' %>');
  $('.answer-' + '<%= answer.id %>').html('<%= j render 'answers/answer_part' %>');
<% end %>